### PR TITLE
Fixes in Turkish translation

### PR DESCRIPTION
**Pull request by iTechsTR**
More accurate word usage and fixes in Turkish translation.

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @itechedit  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by iTechsTR** [comment]
My Github nickname should be iTechsTR instead of itechedit. Make sure to
use the proper username.

**Comment by itechedit** [comment]
Good morning. You have reached the wrong Jim Wells. There is another Jim Wells with a similar alias, so please try re-sending to him. Thanks! — Jim

**Comment by itechedit** [comment]
Good morning. You have reached the wrong Jim Wells. There is another Jim Wells with a similar alias, so please try re-sending this message to him. Thanks! — Jim


Jim Wells, Technical Editor
AQUENT at Microsoft | C+E APEX
APEX editorial service for technical content<https://review.docs.microsoft.com/en-us/help/contribute/contribute-apex-editorial-service>

**Comment by LisandroSu** [comment]
Hello, @iTechsTR 

Thank you for your feedback and suggestion. 
 
The feedback has been partially accepted.. We will adjust  your feedback in order to comply with Microsoft Style Guide. We will release this article in the next localization release round accordingly.

Many thanks for your time and  support on this. 
 
Microsoft C&E Localization Team

**Pull request merged**
